routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('index');

Route::resource('categories', 'CategoryController');
Route::post('categories/{category}/comment', 'CategoryController@comment')
    ->name('categories.comment');

Route::resource('posts', 'PostController')->except(['index']);
Route::post('posts/{post}/comment', 'PostController@comment')
    ->name('posts.comment');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Collection;

class Category extends Model
{
    protected $fillable = ['name', 'description'];
    public $timestamps = false;

    public function getNameAttribute($name)
    {
        return $name ?? 'Имя не задано';
    }

    public function getDescriptionAttribute($description)
    {
        return $description ?? 'Описание не задано';
    }

    /**
     * @return Category[]|Collection
     */
    public static function list() : Collection
    {
        return self::all();
    }

    public function posts()
    {
        return $this->hasMany(Post::class);
    }

    public function comments()
    {
        return $this->morphMany(Comment::class, 'commentable')
            ->orderBy('created_at', 'desc');
    }
}

app/Comment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    protected $fillable = ['content', 'author'];
    const UPDATED_AT = null;

    public function commentable()
    {
        return $this->morphTo();
    }
}

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $fillable = ['name', 'content', 'category_id'];
    public $timestamps = false;

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function comments()
    {
        return $this->morphMany(Comment::class, 'commentable');
    }

    public function attachFile($file)
    {
        $this->filename = $file->store('posts-files', 'public');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class User extends Model
{
    protected $fillable = ['ip', 'browser'];

    protected $primaryKey = 'ip';
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Comment;
use App\Http\Requests\CommentRequest;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class CategoryController extends Controller
{
    public function index()
    {
        $categories = Category::list();

        return view('category.list', compact('categories'));
    }

    public function create()
    {
        return view('category.create');
    }

    public function store(Request $request)
    {
        $category = Category::create($request->all());

        return redirect()->route('categories.show', [$category]);
    }

    public function show(Category $category)
    {
        $category->load(['posts', 'comments']);

        return view('category.show', compact('category'));
    }

    public function edit(Category $category)
    {
        return view('category.edit', compact('category'));
    }

    public function update(Request $request, Category $category)
    {
        $category->update($request->all());

        return redirect()->route('categories.show', $category);
    }

    public function destroy(Category $category)
    {
        $category->delete();

        return redirect()->route('categories.index');
    }

    public function comment(CommentRequest $request, Category $category)
    {
        $comment = new Comment($request->all());
        $category->comments()->save($comment);

        return response()->json('', Response::HTTP_CREATED);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

class HomeController extends Controller
{
    public function index()
    {
        return view('home.index');
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Comment;
use App\Http\Requests\CommentRequest;
use App\Http\Requests\PostRequest;
use App\Post;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class PostController extends Controller
{
    public function create()
    {
        $categories = Category::list();

        return view('post.create', compact('categories'));
    }

    public function store(PostRequest $request)
    {
        $post = new Post($request->all());

        if ($request->hasFile('file')) {
            $post->attachFile($request->file('file'));
        }

        $post->save();

        return redirect()->route('posts.show', $post);
    }

    public function update(PostRequest $request, Post $post)
    {
        if ($request->hasFile('file')) {
            $post->attachFile($request->file('file'));
        }

        $post->update($request->all());

        return redirect()->route('posts.show', $post);
    }

    public function show(Post $post)
    {
        return view('post.show', compact('post'));
    }

    public function edit(Post $post)
    {
        $categories = Category::list();

        return view('post.edit', compact('post', 'categories'));
    }

    public function destroy(Post $post)
    {
        $post->delete();

        return redirect()->route('categories.index');
    }

    public function comment(CommentRequest $request, Post $post)
    {
        $comment = new Comment($request->all());
        $post->comments()->save($comment);

        return response()->json('', Response::HTTP_CREATED);
    }
}

resources/views/category/create.blade.php
@extends('layouts.blog')
@section('title', 'Новая категория')

@section('content')
    <div class="col-md-6 col-md-offset-2">
        <h1 class="text-primary">Новая категория</h1>
        <form method="POST" action="{{ route('categories.store') }}">
            @include('partials.category.createOrUpdateForm')
        </form>
    </div>
@endsection

resources/views/category/edit.blade.php
@extends('layouts.blog')
@section('title', 'Изменение категории')

@section('content')
    <div class="col-md-6 col-md-offset-2">
        <h1 class="text-primary">Изменение категории</h1>
        <form method="POST" action="{{ route('categories.update', $category) }}">
            {{ method_field('put') }}
            @include('partials.category.createOrUpdateForm', compact('category'))
        </form>
    </div>
@endsection

resources/views/category/list.blade.php
@extends('layouts.blog')
@section('title', 'Категории')

@section('css')
    <link rel="stylesheet" href="{{ asset('css/category/list.css') }}">
@endsection
@section('sidebar')
    <a class="btn btn-default" href="{{ route('categories.create') }}">
        <i class="glyphicon glyphicon-plus"></i>
        Добавить категорию
    </a>
@endsection
@section('content')
    <div class="categories row">
        @foreach($categories as $category)
            <div class="col-md-4">
                <div class="category">
                    <h2 class="category-name">
                        <a href="{{ route('categories.show', [$category]) }}">
                            {{ $category->name }} №{{ $category->id }}
                        </a>
                    </h2>
                    <p class="category-description">
                        {{ $category->description }}
                    </p>
                    <div class="row buttons">
                        <form action="{{ route('categories.destroy', $category) }}" method="post" class="btn-group">
                            {{ csrf_field() }}
                            {{ method_field('delete') }}
                            <a class="btn btn-default text-warning" href="{{ route('categories.edit', $category) }}"><i class="glyphicon glyphicon-pencil"></i></a>
                            <button type="submit" class="btn btn-default text-danger">
                                <i class="glyphicon glyphicon-remove"></i>
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        @endforeach
    </div>
@endsection

resources/views/category/show.blade.php
@extends('layouts.blog')
@section('title', $category->name)
@section('css')
    <link rel="stylesheet" href="{{ asset('css/category/show.css') }}">
@endsection
@section('content')
    <h1>Посты категории: <span class="text-primary">{{ $category->name }}</span></h1>
    <div class="row">
        @foreach($category->posts as $post)
            <div class="col-md-4">
                <div class="post">
                    <div class="row">
                        <div class="col-md-4">
                            <a href="{{ route('posts.show', $post) }}">
                                <span class="post-name">{{ $post->name }}</span>
                            </a>
                        </div>
                        <div class="col-md-4">
                            <form action="{{ route('posts.destroy', $post) }}" method="post" class="btn-group">
                                {{ csrf_field() }}
                                {{ method_field('delete') }}
                                <a class="btn btn-sm btn-default text-warning"
                                   href="{{ route('posts.edit', $post) }}"><i
                                            class="glyphicon glyphicon-pencil"></i></a>
                                <button type="submit" class="btn btn-sm btn-default text-danger">
                                    <i class="glyphicon glyphicon-remove"></i>
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        @endforeach
    </div>
@endsection
@section('sidebar')
    <a class="btn btn-default" href="{{ route('posts.create') }}">
        <i class="glyphicon glyphicon-plus"></i>
        Добавить пост
    </a>
    @include('partials.comments', ['url' => route('categories.comment', $category), 'comments' => $category->comments])
@endsection

resources/views/home/index.blade.php
@extends('layouts.blog')
@section('content')
    <ul>
        <li><a href="{{ route('categories.index') }}">Категории</a></li>
        <li><a href="{{ route('categories.create') }}">Добавить категорию</a></li>
        <li><a href="{{ route('posts.create') }}">Добавить пост</a></li>
    </ul>
@endsection

resources/views/layouts/blog.blade.php
<!DOCTYPE html>
<html>
<head>
    {{--jquery--}}
    <script
            src="https://code.jquery.com/jquery-3.3.1.min.js"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
            crossorigin="anonymous"></script>
    {{--bootstrap--}}
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>
    {{--summernote--}}
    <link href="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote.css" rel="stylesheet">
    <script src="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote.js"></script>

    <title>@yield('title', 'Blog')</title>
    @yield('css')
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <a class="navbar-brand" href="{{ route('index') }}">Blog</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li @if (url()->current() == route('categories.index')) class="active" @endif>
                    <a href="{{ route('categories.index') }}">Категории</a>
                </li>
                <li>
                    <a href="{{ route('posts.create') }}">Добавить пост</a>
                </li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>
<div class="content col-md-10">
    @yield('content')
</div>
<aside class="col-md-2">
    <div class="browsers">
        <h4>Браузеры:</h4>
        <ul>
            @foreach($browserStats as $browser)
                <li>{{ $browser->browser }}: {{ $browser->total }}</li>
            @endforeach
        </ul>
    </div>
    @yield('sidebar')
</aside>
@yield('js')
</body>
</html>

resources/views/partials/category/createOrUpdateForm.blade.php
{{ csrf_field() }}
<div class="form-group">
    <label for="name">Название</label>
    <input class="form-control" id="name" type="text" maxlength="255" name="name" value="{{ $category->name ?? '' }}">
</div>
<div class="form-group">
    <label for="description">Описание</label>
    <textarea class="form-control" name="description" id="description" cols="30" rows="5" maxlength="255">
        {{ $category->description ?? '' }}
    </textarea>
</div>
<button class="btn btn-block btn-success">Сохранить</button>

resources/views/partials/comments.blade.php
@section('css')
    <link rel="stylesheet" href="{{ asset('css/comments.css') }}">
@append
@section('js')
    <script>
        var saveCommentUrl = '{{ $url }}';
    </script>
    <script src="{{ asset('js/category/comments.js') }}"></script>
@append
<div class="comments">
    <h4>Комментарии:</h4>
    <div class="row">
        <input placeholder="Автор" class="form-control" type="text" id="author">
    </div>
    <div class="row">
        <textarea placeholder="Комментарий" class="form-control" id="comment" cols="30" rows="5"></textarea>
    </div>
    <div class="row">
        <button class="btn btn-block btn-success" id="add-comment">Добавить</button>
    </div>
    <div class="comments-list row">
        @foreach($comments as $comment)
            <div class="comment">
                <p class="text-primary">{{ $comment->author }}:</p>
                <p>{{ $comment->content }}</p>
            </div>
        @endforeach
    </div>
</div>

resources/views/partials/post/createOrUpdateForm.blade.php
{{ csrf_field() }}
<div class="form-group @if($errors->has('name')){{ 'has-error' }}@endif">
    <label for="name">Название</label>
    <input class="form-control" id="name" type="text" maxlength="255" name="name" value="{{ $post->name ?? '' }}">
    <ul class="text-danger">
        @foreach($errors->get('name') as $error)
            <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
<div class="form-group @if($errors->has('content')){{ 'has-error' }}@endif">
    <label for="content">Описание</label>
    <textarea class="form-control" name="content" id="content" cols="30" rows="5" maxlength="255">
        {{ $post->content ?? '' }}
    </textarea>
    <ul class="text-danger">
        @foreach($errors->get('content') as $error)
            <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
<div class="form-group @if($errors->has('category_id')){{ 'has-error' }}@endif">
    <label for="category">Категория</label>
    <select class="form-control" name="category_id" id="category">
        @foreach($categories as $category)
            <option value="{{ $category->id }}">{{ $category->name }} №{{ $category->id }}</option>
        @endforeach
        <option value="1000">llalala</option>
    </select>
    <ul class="text-danger">
        @foreach($errors->get('category_id') as $error)
            <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
<div class="form-group @if($errors->has('file')){{ 'has-error' }}@endif">
    <label for="file">Файл</label>
    <input type="file" name="file" id="file">
    <ul class="text-danger">
        @foreach($errors->get('file') as $error)
            <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
<button class="btn btn-block btn-success">Сохранить</button>
<script>
    $(document).ready(function() {
         $('#content').summernote({
             height: 200
         });
    });
</script>

resources/views/post/create.blade.php
@extends('layouts.blog')
@section('title', 'Новый пост')

@section('content')
    <div class="col-md-6 col-md-offset-2">
        <h1 class="text-primary">Новый пост</h1>
        <form method="POST" action="{{ route('posts.store') }}" enctype="multipart/form-data">
            @include('partials.post.createOrUpdateForm', compact('categories'))
        </form>
    </div>
@endsection

resources/views/post/edit.blade.php
@extends('layouts.blog')
@section('title', $post->name)

@section('content')
    <div class="col-md-6 col-md-offset-2">
        <h1 class="text-primary">{{ $post->name }}</h1>
        <form method="POST" action="{{ route('posts.update', $post) }}" enctype="multipart/form-data">
            {{ method_field('put') }}
            @include('partials.post.createOrUpdateForm', compact('categories'))
        </form>
    </div>
@endsection

resources/views/post/show.blade.php
@extends('layouts.blog')
@section('title', $post->name)

@section('css')
    <link rel="stylesheet" href="{{ asset('css/post/show.css') }}">
@endsection
@section('content')
    <div class="post">
        <h1>{{ $post->name }}</h1>
        <p>
            {!! $post->content  !!}
        </p>
        @if (!is_null($post->filename))
            <a href="{{ asset('storage/' . $post->filename) }}">Файл</a>
        @else
            <p class="text-danger">Файл не прикреплен</p>
        @endif
    </div>
@endsection
@section('sidebar')
    <a href=""></a>
    @include('partials.comments', ['url' => route('posts.comment', $post), 'comments' => $post->comments])
@endsection